{% set name = "renishaw_wire" %}
{% set version = "0.1.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}



source:
  url: https://github.com/alchem0x2A/py-wdf-reader/archive/refs/tags/{{ version }}.tar.gz
  sha256: 845f488403c736d0b5980c4b1392f6d1c857db0bd415e5d36a2fd82bb9a813af

build:
  number: 0
  noarch: python
  entry_points:
    - wdf-export=renishawWiRE.export:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.12.0
    - python >=3.6
    - matplotlib-base >=2.1.0
    - Pillow >=3.4.0

test:
  imports:
    - renishawWiRE
  commands:
    - pip check
    - wdf-export --help
  requires:
    - pip

about:
  home: https://github.com/alchem0x2A/py-wdf-reader
  summary: Reading wdf Raman spectroscopy file from Renishaw WiRE
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alchem0x2A
